separators:
    geresh: ׳
    gershayim: ״
numerals:
    1: א
    2: ב
    3: ג
    4: ד
    5: ה
    6: ו
    7: ז
    8: ח
    9: ט
    10: י
    20: כ
    30: ל
    40: מ
    50: נ
    60: ס
    70: ע
    80: פ
    90: צ
    100: ק
    200: ר
    300: ש
    400: ת
    500: תק
    600: תר
    700: תש
    800: תת
    900: תתק
specials:
    15: טו
    16: טז
    115: קטו
    116: קטז
    215: רטו
    216: רטז
    270: ער
    272: ערב
    274: עדר
    275: ערה
    298: רחצ
    304: דש
    315: שטו
    316: שטז
    344: שדמ
    415: תטו
    416: תטז
    515: תקטו
    516: תקטז
    615: תרטו
    616: תרטז
    670: עתר
    672: תערב
    674: עדרת
    698: תרחצ
    715: תשטו
    716: תשטז
    744: תשדמ
    815: תתטו
    816: תתטז
    915: תתקטו
    916: תתקטז
  